/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajouter_user (void)
{
  GtkWidget *ajouter_user;
  GtkWidget *fixed1;
  GtkWidget *espritIda;
  GtkWidget *noma;
  GtkWidget *prenoma;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *cina;
  GtkWidget *label8;
  GtkObject *joura_adj;
  GtkWidget *joura;
  GtkObject *moisa_adj;
  GtkWidget *moisa;
  GtkObject *anneea_adj;
  GtkWidget *anneea;
  GtkWidget *label9;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *emaila;
  GtkWidget *tela;
  GtkWidget *label15;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *femmea;
  GSList *femmea_group = NULL;
  GtkWidget *label10;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *afficher;
  GtkWidget *ajouterUser;
  GtkWidget *hommea;
  GtkWidget *rolea;

  ajouter_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_user), _("Ajouter Utilisateur"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajouter_user), fixed1);

  espritIda = gtk_entry_new ();
  gtk_widget_show (espritIda);
  gtk_fixed_put (GTK_FIXED (fixed1), espritIda, 264, 112);
  gtk_widget_set_size_request (espritIda, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (espritIda), 8226);

  noma = gtk_entry_new ();
  gtk_widget_show (noma);
  gtk_fixed_put (GTK_FIXED (fixed1), noma, 160, 168);
  gtk_widget_set_size_request (noma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (noma), 8226);

  prenoma = gtk_entry_new ();
  gtk_widget_show (prenoma);
  gtk_fixed_put (GTK_FIXED (fixed1), prenoma, 432, 168);
  gtk_widget_set_size_request (prenoma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenoma), 8226);

  label5 = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 344, 168);
  gtk_widget_set_size_request (label5, 80, 24);

  label6 = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 88, 224);
  gtk_widget_set_size_request (label6, 57, 25);

  cina = gtk_entry_new ();
  gtk_widget_show (cina);
  gtk_fixed_put (GTK_FIXED (fixed1), cina, 160, 264);
  gtk_widget_set_size_request (cina, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cina), 8226);

  label8 = gtk_label_new (_("CIN:"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 96, 264);
  gtk_widget_set_size_request (label8, 56, 24);

  joura_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  joura = gtk_spin_button_new (GTK_ADJUSTMENT (joura_adj), 1, 0);
  gtk_widget_show (joura);
  gtk_fixed_put (GTK_FIXED (fixed1), joura, 208, 320);
  gtk_widget_set_size_request (joura, 60, 27);

  moisa_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  moisa = gtk_spin_button_new (GTK_ADJUSTMENT (moisa_adj), 1, 0);
  gtk_widget_show (moisa);
  gtk_fixed_put (GTK_FIXED (fixed1), moisa, 328, 320);
  gtk_widget_set_size_request (moisa, 60, 27);

  anneea_adj = gtk_adjustment_new (1, 2000, 2025, 1, 10, 10);
  anneea = gtk_spin_button_new (GTK_ADJUSTMENT (anneea_adj), 1, 0);
  gtk_widget_show (anneea);
  gtk_fixed_put (GTK_FIXED (fixed1), anneea, 464, 320);
  gtk_widget_set_size_request (anneea, 60, 27);

  label9 = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 16, 320);
  gtk_widget_set_size_request (label9, 145, 25);

  label11 = gtk_label_new (_("Mois:"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed1), label11, 272, 320);
  gtk_widget_set_size_request (label11, 57, 25);

  label12 = gtk_label_new (_("Ann\303\251e:"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed1), label12, 400, 320);
  gtk_widget_set_size_request (label12, 57, 25);

  emaila = gtk_entry_new ();
  gtk_widget_show (emaila);
  gtk_fixed_put (GTK_FIXED (fixed1), emaila, 160, 368);
  gtk_widget_set_size_request (emaila, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (emaila), 8226);

  tela = gtk_entry_new ();
  gtk_widget_show (tela);
  gtk_fixed_put (GTK_FIXED (fixed1), tela, 504, 368);
  gtk_widget_set_size_request (tela, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (tela), 8226);

  label15 = gtk_label_new (_("Type d'utilisateur:"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed1), label15, 16, 424);
  gtk_widget_set_size_request (label15, 129, 25);

  label13 = gtk_label_new (_("Email:"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed1), label13, 88, 368);
  gtk_widget_set_size_request (label13, 64, 24);

  label14 = gtk_label_new (_("Numero de tel\303\251phone:"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed1), label14, 336, 368);
  gtk_widget_set_size_request (label14, 160, 24);

  femmea = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (femmea);
  gtk_fixed_put (GTK_FIXED (fixed1), femmea, 352, 224);
  gtk_widget_set_size_request (femmea, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (femmea), femmea_group);
  femmea_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (femmea));

  label10 = gtk_label_new (_("Jour:"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 152, 320);
  gtk_widget_set_size_request (label10, 57, 25);

  label1 = gtk_label_new (_("SMART ESPRIT"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 24, 16);
  gtk_widget_set_size_request (label1, 128, 24);

  label2 = gtk_label_new (_("INSCRIPTION"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 296, 64);
  gtk_widget_set_size_request (label2, 96, 32);

  label3 = gtk_label_new (_("ESPRIT ID:"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 168, 112);
  gtk_widget_set_size_request (label3, 81, 24);

  label4 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 80, 168);
  gtk_widget_set_size_request (label4, 80, 24);

  afficher = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher, 32, 504);
  gtk_widget_set_size_request (afficher, 90, 45);

  ajouterUser = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (ajouterUser);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouterUser, 312, 496);
  gtk_widget_set_size_request (ajouterUser, 136, 48);

  hommea = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (hommea);
  gtk_fixed_put (GTK_FIXED (fixed1), hommea, 160, 224);
  gtk_widget_set_size_request (hommea, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (hommea), femmea_group);
  femmea_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (hommea));

  rolea = gtk_combo_box_entry_new_text ();
  gtk_widget_show (rolea);
  gtk_fixed_put (GTK_FIXED (fixed1), rolea, 160, 424);
  gtk_widget_set_size_request (rolea, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (rolea), _("role1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rolea), _("role2"));

  g_signal_connect ((gpointer) femmea, "toggled",
                    G_CALLBACK (on_femme_toggled),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_user_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouterUser, "clicked",
                    G_CALLBACK (on_ajouterUser_clicked),
                    NULL);
  g_signal_connect ((gpointer) hommea, "toggled",
                    G_CALLBACK (on_homme_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_user, ajouter_user, "ajouter_user");
  GLADE_HOOKUP_OBJECT (ajouter_user, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajouter_user, espritIda, "espritIda");
  GLADE_HOOKUP_OBJECT (ajouter_user, noma, "noma");
  GLADE_HOOKUP_OBJECT (ajouter_user, prenoma, "prenoma");
  GLADE_HOOKUP_OBJECT (ajouter_user, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajouter_user, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajouter_user, cina, "cina");
  GLADE_HOOKUP_OBJECT (ajouter_user, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajouter_user, joura, "joura");
  GLADE_HOOKUP_OBJECT (ajouter_user, moisa, "moisa");
  GLADE_HOOKUP_OBJECT (ajouter_user, anneea, "anneea");
  GLADE_HOOKUP_OBJECT (ajouter_user, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajouter_user, label11, "label11");
  GLADE_HOOKUP_OBJECT (ajouter_user, label12, "label12");
  GLADE_HOOKUP_OBJECT (ajouter_user, emaila, "emaila");
  GLADE_HOOKUP_OBJECT (ajouter_user, tela, "tela");
  GLADE_HOOKUP_OBJECT (ajouter_user, label15, "label15");
  GLADE_HOOKUP_OBJECT (ajouter_user, label13, "label13");
  GLADE_HOOKUP_OBJECT (ajouter_user, label14, "label14");
  GLADE_HOOKUP_OBJECT (ajouter_user, femmea, "femmea");
  GLADE_HOOKUP_OBJECT (ajouter_user, label10, "label10");
  GLADE_HOOKUP_OBJECT (ajouter_user, label1, "label1");
  GLADE_HOOKUP_OBJECT (ajouter_user, label2, "label2");
  GLADE_HOOKUP_OBJECT (ajouter_user, label3, "label3");
  GLADE_HOOKUP_OBJECT (ajouter_user, label4, "label4");
  GLADE_HOOKUP_OBJECT (ajouter_user, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (ajouter_user, ajouterUser, "ajouterUser");
  GLADE_HOOKUP_OBJECT (ajouter_user, hommea, "hommea");
  GLADE_HOOKUP_OBJECT (ajouter_user, rolea, "rolea");

  return ajouter_user;
}

GtkWidget*
create_gestion_des_utilisateurs (void)
{
  GtkWidget *gestion_des_utilisateurs;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *label17;
  GtkWidget *label16;
  GtkWidget *actualiser;
  GtkWidget *ajouterUtilisateur;
  GtkWidget *esId;
  GtkWidget *rechercherUser;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label18;

  gestion_des_utilisateurs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_des_utilisateurs), _("Gestion des utilisateurs"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion_des_utilisateurs), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 24, 64);
  gtk_widget_set_size_request (treeview1, 888, 544);

  label17 = gtk_label_new (_("Gestion des utilisateurs"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 520, 8);
  gtk_widget_set_size_request (label17, 240, 56);

  label16 = gtk_label_new (_("SMART ESPRIT"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 8, 0);
  gtk_widget_set_size_request (label16, 128, 48);

  actualiser = gtk_button_new_with_mnemonic (_("Acualiser"));
  gtk_widget_show (actualiser);
  gtk_fixed_put (GTK_FIXED (fixed2), actualiser, 32, 608);
  gtk_widget_set_size_request (actualiser, 88, 40);

  ajouterUtilisateur = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (ajouterUtilisateur);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouterUtilisateur, 136, 608);
  gtk_widget_set_size_request (ajouterUtilisateur, 96, 40);

  esId = gtk_entry_new ();
  gtk_widget_show (esId);
  gtk_fixed_put (GTK_FIXED (fixed2), esId, 32, 32);
  gtk_widget_set_size_request (esId, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (esId), 8226);

  rechercherUser = gtk_button_new ();
  gtk_widget_show (rechercherUser);
  gtk_fixed_put (GTK_FIXED (fixed2), rechercherUser, 208, 32);
  gtk_widget_set_size_request (rechercherUser, 120, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (rechercherUser), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox1), label18, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "popup_menu",
                    G_CALLBACK (on_treeview1_popup_menu),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "button_press_event",
                    G_CALLBACK (on_treeview1_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouterUtilisateur, "clicked",
                    G_CALLBACK (on_ajouterUtilisateur_clicked),
                    NULL);
  g_signal_connect ((gpointer) rechercherUser, "clicked",
                    G_CALLBACK (on_rechercherUser_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_des_utilisateurs, gestion_des_utilisateurs, "gestion_des_utilisateurs");
  GLADE_HOOKUP_OBJECT (gestion_des_utilisateurs, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_des_utilisateurs, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion_des_utilisateurs, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_des_utilisateurs, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestion_des_utilisateurs, actualiser, "actualiser");
  GLADE_HOOKUP_OBJECT (gestion_des_utilisateurs, ajouterUtilisateur, "ajouterUtilisateur");
  GLADE_HOOKUP_OBJECT (gestion_des_utilisateurs, esId, "esId");
  GLADE_HOOKUP_OBJECT (gestion_des_utilisateurs, rechercherUser, "rechercherUser");
  GLADE_HOOKUP_OBJECT (gestion_des_utilisateurs, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (gestion_des_utilisateurs, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (gestion_des_utilisateurs, image1, "image1");
  GLADE_HOOKUP_OBJECT (gestion_des_utilisateurs, label18, "label18");

  return gestion_des_utilisateurs;
}

GtkWidget*
create_modifier_user (void)
{
  GtkWidget *modifier_user;
  GtkWidget *fixed3;
  GtkWidget *espritIdm;
  GtkWidget *nomm;
  GtkWidget *prenomm;
  GtkWidget *cinm;
  GtkObject *jourm_adj;
  GtkWidget *jourm;
  GtkObject *moism_adj;
  GtkWidget *moism;
  GtkWidget *emailm;
  GtkWidget *telm;
  GtkObject *anneem_adj;
  GtkWidget *anneem;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label123;
  GtkWidget *labelkk;
  GtkWidget *label32;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label27;
  GtkWidget *label26;
  GtkWidget *label25;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *modifierUser;
  GtkWidget *retourU;
  GtkWidget *hommem;
  GSList *hommem_group = NULL;
  GtkWidget *femmem;
  GtkWidget *rolem;
  GtkWidget *labelkbn;

  modifier_user = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_user), _("Modifier Utilisateur"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifier_user), fixed3);

  espritIdm = gtk_entry_new ();
  gtk_widget_show (espritIdm);
  gtk_fixed_put (GTK_FIXED (fixed3), espritIdm, 304, 112);
  gtk_widget_set_size_request (espritIdm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (espritIdm), 8226);

  nomm = gtk_entry_new ();
  gtk_widget_show (nomm);
  gtk_fixed_put (GTK_FIXED (fixed3), nomm, 184, 168);
  gtk_widget_set_size_request (nomm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomm), 8226);

  prenomm = gtk_entry_new ();
  gtk_widget_show (prenomm);
  gtk_fixed_put (GTK_FIXED (fixed3), prenomm, 472, 168);
  gtk_widget_set_size_request (prenomm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenomm), 8226);

  cinm = gtk_entry_new ();
  gtk_widget_show (cinm);
  gtk_fixed_put (GTK_FIXED (fixed3), cinm, 184, 280);
  gtk_widget_set_size_request (cinm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinm), 8226);

  jourm_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jourm = gtk_spin_button_new (GTK_ADJUSTMENT (jourm_adj), 1, 0);
  gtk_widget_show (jourm);
  gtk_fixed_put (GTK_FIXED (fixed3), jourm, 232, 336);
  gtk_widget_set_size_request (jourm, 60, 27);

  moism_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  moism = gtk_spin_button_new (GTK_ADJUSTMENT (moism_adj), 1, 0);
  gtk_widget_show (moism);
  gtk_fixed_put (GTK_FIXED (fixed3), moism, 360, 336);
  gtk_widget_set_size_request (moism, 60, 27);

  emailm = gtk_entry_new ();
  gtk_widget_show (emailm);
  gtk_fixed_put (GTK_FIXED (fixed3), emailm, 184, 392);
  gtk_widget_set_size_request (emailm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (emailm), 8226);

  telm = gtk_entry_new ();
  gtk_widget_show (telm);
  gtk_fixed_put (GTK_FIXED (fixed3), telm, 528, 392);
  gtk_widget_set_size_request (telm, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (telm), 8226);

  anneem_adj = gtk_adjustment_new (2000, 2000, 2050, 1, 10, 10);
  anneem = gtk_spin_button_new (GTK_ADJUSTMENT (anneem_adj), 1, 0);
  gtk_widget_show (anneem);
  gtk_fixed_put (GTK_FIXED (fixed3), anneem, 496, 336);
  gtk_widget_set_size_request (anneem, 60, 27);

  label19 = gtk_label_new (_("SMART ESPRIT"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 8, 24);
  gtk_widget_set_size_request (label19, 160, 24);

  label20 = gtk_label_new (_("Modifier user"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 312, 64);
  gtk_widget_set_size_request (label20, 144, 32);

  label123 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label123);
  gtk_fixed_put (GTK_FIXED (fixed3), label123, 104, 168);
  gtk_widget_set_size_request (label123, 65, 25);

  labelkk = gtk_label_new (_("ESPRITID:"));
  gtk_widget_show (labelkk);
  gtk_fixed_put (GTK_FIXED (fixed3), labelkk, 208, 112);
  gtk_widget_set_size_request (labelkk, 89, 25);

  label32 = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed3), label32, 384, 168);
  gtk_widget_set_size_request (label32, 73, 25);

  label23 = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 96, 232);
  gtk_widget_set_size_request (label23, 89, 25);

  label24 = gtk_label_new (_("CIN:"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 104, 280);
  gtk_widget_set_size_request (label24, 73, 25);

  label27 = gtk_label_new (_("Mois:"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed3), label27, 304, 336);
  gtk_widget_set_size_request (label27, 49, 25);

  label26 = gtk_label_new (_("Jour:"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed3), label26, 176, 336);
  gtk_widget_set_size_request (label26, 57, 25);

  label25 = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 16, 336);
  gtk_widget_set_size_request (label25, 161, 25);

  label29 = gtk_label_new (_("Email:"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed3), label29, 96, 392);
  gtk_widget_set_size_request (label29, 81, 24);

  label30 = gtk_label_new (_("Num\303\251ro de tel\303\251phone:"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed3), label30, 352, 392);
  gtk_widget_set_size_request (label30, 185, 24);

  label31 = gtk_label_new (_("Type d'utilisateur:"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed3), label31, 8, 448);
  gtk_widget_set_size_request (label31, 161, 25);

  modifierUser = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (modifierUser);
  gtk_fixed_put (GTK_FIXED (fixed3), modifierUser, 336, 504);
  gtk_widget_set_size_request (modifierUser, 120, 40);

  retourU = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (retourU);
  gtk_fixed_put (GTK_FIXED (fixed3), retourU, 16, 512);
  gtk_widget_set_size_request (retourU, 74, 45);

  hommem = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (hommem);
  gtk_fixed_put (GTK_FIXED (fixed3), hommem, 184, 232);
  gtk_widget_set_size_request (hommem, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (hommem), hommem_group);
  hommem_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (hommem));

  femmem = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (femmem);
  gtk_fixed_put (GTK_FIXED (fixed3), femmem, 384, 232);
  gtk_widget_set_size_request (femmem, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (femmem), hommem_group);
  hommem_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (femmem));

  rolem = gtk_combo_box_entry_new_text ();
  gtk_widget_show (rolem);
  gtk_fixed_put (GTK_FIXED (fixed3), rolem, 184, 448);
  gtk_widget_set_size_request (rolem, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (rolem), _("role1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rolem), _("role2"));

  labelkbn = gtk_label_new (_("Ann\303\251e:"));
  gtk_widget_show (labelkbn);
  gtk_fixed_put (GTK_FIXED (fixed3), labelkbn, 432, 336);
  gtk_widget_set_size_request (labelkbn, 57, 25);

  g_signal_connect ((gpointer) modifierUser, "clicked",
                    G_CALLBACK (on_modifierUser_clicked),
                    NULL);
  g_signal_connect ((gpointer) retourU, "clicked",
                    G_CALLBACK (on_retourU_clicked),
                    NULL);
  g_signal_connect ((gpointer) hommem, "toggled",
                    G_CALLBACK (on_hommem_toggled),
                    NULL);
  g_signal_connect ((gpointer) femmem, "toggled",
                    G_CALLBACK (on_femmem_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_user, modifier_user, "modifier_user");
  GLADE_HOOKUP_OBJECT (modifier_user, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifier_user, espritIdm, "espritIdm");
  GLADE_HOOKUP_OBJECT (modifier_user, nomm, "nomm");
  GLADE_HOOKUP_OBJECT (modifier_user, prenomm, "prenomm");
  GLADE_HOOKUP_OBJECT (modifier_user, cinm, "cinm");
  GLADE_HOOKUP_OBJECT (modifier_user, jourm, "jourm");
  GLADE_HOOKUP_OBJECT (modifier_user, moism, "moism");
  GLADE_HOOKUP_OBJECT (modifier_user, emailm, "emailm");
  GLADE_HOOKUP_OBJECT (modifier_user, telm, "telm");
  GLADE_HOOKUP_OBJECT (modifier_user, anneem, "anneem");
  GLADE_HOOKUP_OBJECT (modifier_user, label19, "label19");
  GLADE_HOOKUP_OBJECT (modifier_user, label20, "label20");
  GLADE_HOOKUP_OBJECT (modifier_user, label123, "label123");
  GLADE_HOOKUP_OBJECT (modifier_user, labelkk, "labelkk");
  GLADE_HOOKUP_OBJECT (modifier_user, label32, "label32");
  GLADE_HOOKUP_OBJECT (modifier_user, label23, "label23");
  GLADE_HOOKUP_OBJECT (modifier_user, label24, "label24");
  GLADE_HOOKUP_OBJECT (modifier_user, label27, "label27");
  GLADE_HOOKUP_OBJECT (modifier_user, label26, "label26");
  GLADE_HOOKUP_OBJECT (modifier_user, label25, "label25");
  GLADE_HOOKUP_OBJECT (modifier_user, label29, "label29");
  GLADE_HOOKUP_OBJECT (modifier_user, label30, "label30");
  GLADE_HOOKUP_OBJECT (modifier_user, label31, "label31");
  GLADE_HOOKUP_OBJECT (modifier_user, modifierUser, "modifierUser");
  GLADE_HOOKUP_OBJECT (modifier_user, retourU, "retourU");
  GLADE_HOOKUP_OBJECT (modifier_user, hommem, "hommem");
  GLADE_HOOKUP_OBJECT (modifier_user, femmem, "femmem");
  GLADE_HOOKUP_OBJECT (modifier_user, rolem, "rolem");
  GLADE_HOOKUP_OBJECT (modifier_user, labelkbn, "labelkbn");

  return modifier_user;
}

